# Generated by Django 4.2 on 2025-05-06 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExerciceBudgetaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.IntegerField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("provisoire", "Provisoire"),
                            ("definitif", "Définitif"),
                            ("clos", "Clos"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imputation", models.CharField(max_length=100)),
                ("nom", models.CharField(max_length=100)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("fiscale", "Fiscale"),
                            ("douanière", "Douanière"),
                            ("dons", "Dons"),
                            ("emprunts", "Emprunts"),
                            ("autres", "Autres"),
                        ],
                        max_length=50,
                    ),
                ),
                ("montantPrevu", models.IntegerField()),
                ("montantAutorise", models.IntegerField()),
                ("montantRealise", models.IntegerField()),
                (
                    "exercice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget.exercicebudgetaire",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Depense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapitre", models.CharField(max_length=100)),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("fonctionnement", "Fonctionnement"),
                            ("investissement", "Investissement"),
                        ],
                        max_length=50,
                    ),
                ),
                ("paragraphe", models.CharField(max_length=100)),
                (
                    "fonction",
                    models.CharField(
                        choices=[
                            ("souveraineté", "Souveraineté"),
                            ("santé", "Santé"),
                            ("sécurité", "Sécurité"),
                        ],
                        max_length=50,
                    ),
                ),
                ("montantPrevu", models.IntegerField()),
                ("montantAutorise", models.IntegerField()),
                ("montantRealise", models.IntegerField()),
                (
                    "exercice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget.exercicebudgetaire",
                    ),
                ),
            ],
        ),
    ]
