# Generated by Django 4.2 on 2025-05-06 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=32, verbose_name="Nom de la personne"),
                ),
                (
                    "prenom",
                    models.CharField(
                        max_length=32, verbose_name="Prénom de la personne"
                    ),
                ),
                ("datenais", models.DateField(verbose_name="Date de naissance")),
            ],
        ),
    ]
